name: services/testservice

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_VAR}}
    steps:
    - name: Print test code to the console
      uses: actions/checkout@v4
      
    - name: List Environment Variables
      run: |
        echo "AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}"
        echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"
      
    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: milrainregistry.azurecr.io
        username: ${{ vars.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
    - name: List containers in ACR
      run: az acr list -g test -o table
  

