name: services/testservice

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print test code to the console
      uses: actions/checkout@v4
      
    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: milrainregistry.azurecr.io
        username: ${{ vars.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
  

