name: services/testservice

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - main
    
jobs:
  login:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: Print test code to the console
      uses: actions/checkout@v4
      
    - name: List Environment Variables
      run: |
        echo "AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}"
        echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"

    - name: Log into Azure
      run: |
        output=$(az login --service-principal -u ${{ vars.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} -t 6b902c69-e591-4cfb-a7a7-8fa0efbbea01)
        echo $output

    - name: Log into to ACR
      run: |
        output=$(az acr login --name milrainregistry)
        echo $output

    - name: List containers in ACR
      run: |
        output=$(az acr list -g test -o table)
        echo $output

    - name: Login to ACR via Docker
      uses: docker/login-action@v3
      with:
        registry: milrainregistry.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
  

